title: Extra182
description: Hello, we're students at Faculty of Computer Science, <br/>
University of Indonesia. <br/>
In this part we're gonna talk about how to use jekyll static generator properly to our github pages. <br/>
But first, please allow us to introduce ourselves; <br/>
Fadhriz Q. A. <br/>
Nardiena A. P. <br/>
Wahyu A.D.T. <br/>
theme: jekyll-theme-leap-day
encoding: UTF-8
timezone: Asia/Jakarta
show_downloads: true
share: true
#google_analytics: UA-89852122-1
plugins:
  -jekyll-gist
  -jemoji
markdown: kramdown
github: [metadata]
